% this script is written to compare strain fields generated by processed
% grid data to those generated from pure FE data

%Author: Andrew Matejunas

%% initialize
clear all, close all, clc

%% choose data files to load
FEdata=uigetfile('.mat','Choose FE data file');
GMdata=uigetfile('.mat','Choose GM datafile');
Cordata=uigetfile('.mat','Choose Corrected GM datafile');
desig=char(inputdlg('input test designation'));

%% Load Data files
fprintf('loading FEdata \n')
FE=load(FEdata)
fprintf('loading GMdata \n')
GM=load(GMdata)
fprintf('loading corrected GM data \n')
Cor=load(Cordata)

testdeg=desig;
clear desig

%% define limits based on pure FE data
XYstrainlim=[min(FE.strain.s,[],'all'),max(FE.strain.s,[],'all')];
XXstrainlim=[min(FE.strain.x,[],'all'),max(FE.strain.x,[],'all')];

%% Create X and Y vectors
X_vecGM=GM.pos.x*10^3;
Y_vecGM=GM.pos.y'*10^3;

X_vecCor=Cor.pos.x*10^3;
Y_vecCor=Cor.pos.y'*10^3;

X_vecFE=FE.pos.x*10^3;
Y_vecFE=FE.pos.y'*10^3;

%% Set time vectors
timemic=GM.time.vec*10^6; %us

%% Generate plots
figure('units','normalized','outerposition',[0 0 1 1])

for n=1:length(timemic)
   timecount=num2str(timemic(n)); 
   framecount=num2str(n); 
  
   
   XYstrainFE=squeeze(FE.strain.s(:,:,n));
   XYstrainGM=squeeze(GM.strain.s(:,:,n));
   XYstrainCor=squeeze(Cor.strain.s(:,:,n));
   
   XXstrainFE=squeeze(FE.strain.x(:,:,n));
   XXstrainGM=squeeze(GM.strain.x(:,:,n));
   XXstrainCor=squeeze(Cor.strain.x(:,:,n));
  
   
   
   %% Plot FE strains
    subplot(3,2,1)
    imagesc(X_vecFE,Y_vecFE,XXstrainFE)
    title(strcat('FE strain_{xx} ',timecount,'\mus'))
    xlabel('X coordinate (mm)')
    ylabel('Y coordinate (mm)')
    colormap('hot')
    cx=colorbar;
    cx.Label.String='strain';
    caxis(XXstrainlim)
    
    subplot(3,2,2)
    imagesc(X_vecFE,Y_vecFE,XYstrainFE)
    title(strcat('FE shear Strain ',timecount,'\mus'))
    xlabel('X coordinate (mm)')
    ylabel('Y coordinate (mm)')
    colormap('hot')
    cx=colorbar;
    cx.Label.String='shear strain';
    caxis(XYstrainlim)
    
  %% plot GM strains
    subplot(3,2,3)
    imagesc(X_vecGM,Y_vecGM,XXstrainGM)
    title(strcat('Grid Method ',timecount,'\mus'))
    xlabel('X coordinate (mm)')
    ylabel('Y coordinate (mm)')
    colormap('hot')
    cx=colorbar;
    cx.Label.String='strain';
    caxis(XXstrainlim)
    
    subplot(3,2,4)
    imagesc(X_vecGM,Y_vecGM,XYstrainGM)
    title(strcat('Grid Method shear Strain ',timecount,'\mus'))
    xlabel('X coordinate (mm)')
    ylabel('Y coordinate (mm)')
    colormap('hot')
    cx=colorbar;
    cx.Label.String='shear strain';
    caxis(XYstrainlim)
    
  %% plot rates
  subplot(3,2,5)
    imagesc(X_vecCor,Y_vecCor,XXstrainCor)
    title(strcat('Corrected Grid Method ',timecount,'\mus'))
    xlabel('X coordinate (mm)')
    ylabel('Y coordinate (mm)')
    colormap('hot')
    cx=colorbar;
    cx.Label.String='strain';
    caxis(XXstrainlim)
    
    subplot(3,2,6)
    imagesc(X_vecCor,Y_vecCor,XYstrainCor)
    title(strcat('Corrected shear Strain ',timecount,'\mus'))
    xlabel('X coordinate (mm)')
    ylabel('Y coordinate (mm)')
    colormap('hot')
    cx=colorbar;
    cx.Label.String='shear strain';
    caxis(XYstrainlim)
    
 saveas(gcf,strcat(testdeg,'_CorrEval_',framecount,'.fig'))
 saveas(gcf,strcat(testdeg,'_CorrEval_',framecount,'.png'))
end
